# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de345c99d10f8ff9983567f9f66ce0062b15e44028a35849823842464276caaf2faabf79c6355b3163708dc5af1f9cd3c71a11cb87748e03fa6bebff74fd0cad

test:
  secret_key_base: a4bf9c9ae21bf77de2a22de96f7fccedcb7759440f9efaa357de2267c2d6cbfe651ff6ab6fe47aed309fda4e6bbddf9b1069fe3406a66a34ebf94a25d5a393a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
