# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c9eaa45d0e670c18e3452fdd644d79496e1813cc586a60f21a73311351337413b2a60c157722db113d637df9937861b49f79cc64630d4067febd19072725d6

test:
  secret_key_base: 1960b93dbf6edb9ba2e375d84554b573a9f5759224048edb2c8bc24020867f167bfc6a53121e4a0d84a89e375266480f8820c52050edb86b9860ba9c52488b3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
